const routesConfig = {
  home: "/",
  login: "/login",
  products: "/products",
  productDetails: "/productDetails",
  categoryProducts: "/category",
  deposit: "/deposit",
  registerShop: "/registerShop",
  register: "/register",
  account: "/account",
  paymentHistory: "/paymentHistory",
  contentManager: "/contentManager",
  changePassword: "/changePassword",
  support: "/support",
  share: "/share",
  faqs: "/faqs",
  forgotPassword: "/forgotPassword",
  infoAccount: "/infoAccount",
  userProfile: "/userProfile",
  loginValidator: "/loginValidator",
  getProductDetailsUrl: (id: number) => `/productDetails/${id}`,
  getProductUrl: (id: number) => `/product/${id}`,
  getCategoryProductsUrl: (id: number) => `/category/${id}`,
  changePasswordUrl: "/changePassword",
  userOrder: "/userOrder",
  orderReceipt: "/order-receipt",
  sellerDashboard: "/seller/dashboard",
  sellerProducts: "/seller/products",
  sellerOrders: "/seller/orders",
  sellerShop: "/seller/shop",
  adminDashboard: "/admin/dashboard",
  adminProducts: "/admin/products",
  orders: "/userOrder", // Alias cho userOrder để tương thích với code cũ
  getOrderReceiptUrl: (orderId: number) => `/order-receipt/${orderId}`,
};

export default routesConfig;
